config/routes.rb
Rails.application.routes.draw do

  get 'users/show'
  get 'contact/index'
  devise_for :users
  resources :user_logins, only: [:new]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'landings#index'
  resources :items, path: 'chat' do
    resources :orders
    resources :comments
  end
  resources :carts, only: [:index, :create, :show, :update, :destroy], path: 'panier'
  resources :users, only: [:show, :update, :edit], path: 'profil'
  resources :charges, only: [:new, :create]
  resources :contact, only: [:index], path: 'contact'





end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :comment
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :comments
    has_one_attached :picture
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :orders
  has_many :comments
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include CartsHelper
  before_action :authenticate_user

  def index
    @cart = current_cart
  end

  def create
    :authenticate_user
    @cart_item = CartItem.new(permit_params)
    unless (already_in_cart(@cart_item))
      if @cart_item.save
        respond_to do |format|
          format.js { }
        end
      else 
        flash.now[:error] = puts @cart_item.errors.messages
        render 'chat'
      end
    end
  end

  def new
  end

  def update
  end

  def show
    @cart = current_cart
    respond_to do |format|
      format.html { redirect_to '/' }
      format.js { }
    end
  end

  def destroy
    CartItem.find(params[:id].to_i).destroy
    @cart = current_cart
    respond_to do |format|
      format.html { redirect_to carts_path }
      format.js { }
    end
  end

  private

  def find_price
    return Item.find(params[:item_id].to_i).price
  end

  def permit_params
    params[:price] = find_price
    params[:user_id] = current_user.id
    params.permit(:item_id, :user_id, :quantity, :price)
  end

  def authenticate_user
    unless (user_signed_in?)
      redirect_to user_session_path
    end
  end

  def permit_params
    params[:price] = find_price
    params[:user_id] = current_user.id
    params.permit(:item_id, :user_id, :quantity, :price)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(permit_params)
    @item.picture.attach(params[:cat_picture])
    if @item.save
      redirect_to items_path
    else
      flash.now[:errors] = "There were those errors : "
      render new_item_path
    end
  end

  def destroy
    Item.find(params[:id]).destroy
  end

  def update
    Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  private

  def permit_params
    params.permit(:name, :price)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user= current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
    def current_cart
        @current_cart = []
        @cart_items = CartItem.all
        @cart_items.each do |item|
            if item.user_id == current_user.id
                @current_cart << item
            end
        end
    end

    def cart_total
        @price = 0
        current_cart.each do |cart_item|
            @price += Item.find(cart_item.item_id).price
        end
        return @price
    end

    def already_in_cart(new_cart_item)
        @cart_items = current_cart
        @cart_items.each do |item|
            if item.item_id == new_cart_item.item_id
                return true
            end
        end
        return false
    end

    def destroy_cart
        @cart_items = CartItem.all
        @cart_items.each do |item|
            if item.user_id == current_user.id
                item.destroy
            end
        end
    end
end

app/helpers/charges_helper.rb
module ChargesHelper
    def calculate_order_amount
        clear_orders
        @amount = 0
        @orders = Order.all
        @orders.each do |order|
            if order.customer_id == current_user.id && !order.achieved
                @amount += Item.find(order.item_id).price
            end
        end
        return @amount
    end

    def clear_orders
        @orders = Order.all
        @orders.each do |order|
            if !order.achieved
                d = false
                Item.all.each do |item|
                    if item.id == order.id
                        d = true
                    end
                end
                order.destroy if d
            end
        end
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/create.html.erb
<h1>Carts#create</h1>
<p>Find me in app/views/carts/create.html.erb</p>

app/views/carts/create.js.erb
console.log("okay")

app/views/carts/destroy.js.erb
if (document.getElementById("cart")) { document.getElementById("cart").remove() }
document.getElementsByTagName("body")[0].insertAdjacentHTML("beforeend", "<%= j render 'updated_cart' %>")

app/views/carts/index.html.erb
<% @disable_nav = true %>

<div class="buying-page">
    <div class="item-infos border border-warning">
        <div class="cart-elements-index">
            <% @cart.each do |item| %>
                <div class="index-cart-items">
                    <%= image_tag(Item.find(item.item_id).picture) if Item.find(item.item_id).picture.attached?  %>
                    <a href="<%= new_charge_path %>" class="nav-link text-dark" ><%= Item.find(item.item_id).name %><br>$<%= item.price %></a>
                    <%= link_to "Enlever", cart_path(item.id), method: :delete, class: "nav-link text-danger" %>
                </div>
            <% end %>
        </div>
        <%= form_with url: charges_path, method: :post do |f|%>
            <%= f.hidden_field :from_cart, value: true %>
            <article>
                <% if flash[:error].present? %>
                    <div id="error_explanation">
                        <p><%= flash[:error] %></p>
                    </div>
                <% end %>
            </article>
            <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                    data-description="Informations"
                    data-amount="<%= cart_total * 100 %>"
                    data-locale="auto"></script>
        <% end %>
    </div>
</div>

app/views/carts/new.html.erb
<h1>Carts#new</h1>
<p>Find me in app/views/carts/new.html.erb</p>

app/views/carts/show.html.erb
<% item = Item.find(params[:id].to_i) %>
<%= image_tag(item.picture) if item.picture.attached?  %>

app/views/carts/show.js.erb
if (document.getElementById("cart")) { document.getElementById("cart").remove() }
document.getElementsByTagName("body")[0].insertAdjacentHTML("beforeend", "<%= j render 'cart' %>")

app/views/carts/update.html.erb
<h1>Carts#update</h1>
<p>Find me in app/views/carts/update.html.erb</p>