config/routes.rb
Rails.application.routes.draw do

  get 'users/show'
  get 'contact/index'
  devise_for :users
  resources :user_logins, only: [:new]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'landings#index'
  resources :items, path: 'chat' do
    resources :orders
    resources :comments
  end
  resources :carts, only: [:index, :create, :show, :update, :destroy], path: 'panier'
  resources :users, only: [:show, :update, :edit], path: 'profil'
  resources :charges, only: [:new, :create]
  resources :contact, only: [:index], path: 'contact'





end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :comment
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :comments
    has_one_attached :picture
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :orders
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include CartsHelper
    include ChargesHelper
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include CartsHelper
  before_action :authenticate_user

  def index
    @cart = current_cart
  end

  def create
    :authenticate_user
    @cart_item = CartItem.new(permit_params)
    unless (already_in_cart(@cart_item))
      if @cart_item.save
        respond_to do |format|
          format.js { }
        end
      else 
        flash.now[:error] = puts @cart_item.errors.messages
        render 'chat'
      end
    end
  end

  def new
  end

  def update
  end

  def show
    @cart = current_cart
    respond_to do |format|
      format.html { redirect_to '/' }
      format.js { }
    end
  end

  def destroy
    CartItem.find(params[:id].to_i).destroy
    @cart = current_cart
    respond_to do |format|
      format.html { redirect_to carts_path }
      format.js { }
    end
  end

  private

  def find_price
    return Item.find(params[:item_id].to_i).price
  end

  def permit_params
    params[:price] = find_price
    params[:user_id] = current_user.id
    params.permit(:item_id, :user_id, :quantity, :price)
  end

  def authenticate_user
    unless (user_signed_in?)
      redirect_to user_session_path
    end
  end

  def permit_params
    params[:price] = find_price
    params[:user_id] = current_user.id
    params.permit(:item_id, :user_id, :quantity, :price)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(permit_params)
    @item.picture.attach(params[:cat_picture])
    if @item.save
      redirect_to items_path
    else
      flash.now[:errors] = "There were those errors : "
      render new_item_path
    end
  end

  def destroy
    Item.find(params[:id]).destroy
  end

  def update
    Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  private

  def permit_params
    params.permit(:name, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
    def current_cart
        @current_cart = []
        @cart_items = CartItem.all
        @cart_items.each do |item|
            if item.user_id == current_user.id
                @current_cart << item
            end
        end
    end

    def cart_total
        @price = 0
        current_cart.each do |cart_item|
            @price += Item.find(cart_item.item_id).price
        end
        return @price
    end

    def already_in_cart(new_cart_item)
        @cart_items = current_cart
        @cart_items.each do |item|
            if item.item_id == new_cart_item.item_id
                return true
            end
        end
        return false
    end

    def destroy_cart
        @cart_items = CartItem.all
        @cart_items.each do |item|
            if item.user_id == current_user.id
                item.destroy
            end
        end
    end
end

app/helpers/charges_helper.rb
module ChargesHelper
    def calculate_order_amount
        clear_orders
        @amount = 0
        @orders = Order.all
        @orders.each do |order|
            if order.customer_id == current_user.id && !order.achieved
                @amount += Item.find(order.item_id).price
            end
        end
        return @amount
    end

    def clear_orders
        @orders = Order.all
        @orders.each do |order|
            if !order.achieved
                d = false
                Item.all.each do |item|
                    if item.id == order.id
                        d = true
                    end
                end
                order.destroy if d
            end
        end
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_cart.html.erb
<div class="cart-body border border-warning" id="cart">
    <div class="cart-title">
        <h4>Panier</h4>
    </div>
    <div class="cart-elements">
        <% @cart.each do |item| %>
            <div>
                <a href="<%= new_charge_path %>" class="nav-link text-dark" ><%= Item.find(item.item_id).name %><br>$<%= item.price %></a>
                <%= link_to "Enlever", cart_path(item.id), method: :delete, remote: true, class: "nav-link text-danger" %>
            </div>
        <% end %>
    </div>
    <div class="bottom-payment">
        <%= link_to "Total : $#{cart_total}", carts_path, method: :get, class: "btn btn-sm btn-warning" %>
    </div>
</div>

app/views/application/_footer.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
<link href="../app/assets/stylesheets/application.css">

<footer class="footer py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="/" class="nav-link px-2 text-white">Home</a></li>
      <li class="nav-item"><a href="<%= items_path %>" class="nav-link px-2 text-white">Pictures</a></li>
      <li class="nav-item"><a href="contact#index" class="nav-link px-2 text-white">Contact</a></li>
    </ul>
    <p class="text-center text-white">© By the dream team</p>
  </footer>

app/views/application/_in_cart.html.erb
<div class="bg-success text-success in-cart">
    <p>Added to cart</p>
</div>

app/views/application/_item_list.html.erb
<div class="item-list">
    <% @items.each do |item| %>
    <div class="item-image hoverable">
        <%= image_tag(item.picture) if item.picture.attached?  %>
        <div id="photo<%= item.id %>" class="collapse buying-div">
                <%= form_with url: carts_path(item.id), method: :post, remote: true do |form| %>
                    <%= form.hidden_field :item_id, value: item.id %>
                    <%= form.hidden_field :quantity, value: 1 %><br>
                    <%= form.submit "Panier", class: "bb btn btn-sm btn-outline-warning" %>
                <% end %>
                <br>
                <%= link_to "Acheter", item_path(item.id), method: :get, class: "bb btn btn-sm btn-outline-warning" %>
                <p class="price">$<%= item.price %></p>
        </div>
    </div>
    <% end %>
</div>

<script>
    items = document.getElementsByClassName("hoverable")
    for (let i = 0; i < items.length; i++){
        items[i].addEventListener("mouseover", function(){
            document.getElementsByClassName("buying-div")[i].classList.toggle("collapse")
            document.getElementsByClassName("buying-div")[i].classList.toggle("darken")
        })
    }
    for (let i = 0; i < items.length; i++){
        items[i].addEventListener("mouseout", function(){
            document.getElementsByClassName("buying-div")[i].classList.toggle("collapse")
            document.getElementsByClassName("buying-div")[i].classList.toggle("darken")
        })
    }

    document.getElementsByTagName("body")[0].addEventListener("click", function(){
        if (document.getElementById("cart")) {
            document.getElementById("cart").remove()
        }
    })
</script>

app/views/application/_landing.html.erb
<div class="flex-land">
  <div class="left-div twin"></div>
  <div class="right-div twin"><a href="chat" class="land-name"><h1 class="display-3"><b>The <i class="text-warning">Cats</i> we love to <b>adore</b></h1></a><br>
  
  </div>  
</div>

<script>
  window.addEventListener("mousemove", function(e){
    document.getElementsByClassName("right-div")[0].style.transform = `translate(${e.clientX / 100}%, ${e.clientY / 100}%)`
  })
</script>

app/views/application/_login.html.erb
<div class="login-body">   
  <div class="login-outer border border-warning">
    <div class="login" >
      <br><h2>Log in<b class="text-warning">.</b></h2><br>

      <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
      <div class="form-inputs">

        <div class="form-group mb-4">
          <%= f.input :email,
                required: false,
                autofocus: true,
                input_html: { autocomplete: "email" } %>
                </div>

      <div class="form-group mb-4">
          <%= f.input :password,
                required: false,
                input_html: { autocomplete: "current-password" } %>
                </div>

      <div class="form-group mb-4">
          <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
                </div>
                </div>

        <div class="form-actions">
          <%= f.button :submit, "Log in", class: "btn btn-lg btn-warning btn-block" %>
        </div><br>
      <% end %>

      <%= render "devise/shared/links" %>
    </div>
  </div>
</div>

app/views/application/_nav.html.erb
    <div class="cats-nav">
      <div class="cat-nav-shadow">
        <ul>
        <li class="nav-item">
            <a class="nav-link" href="/">HOME</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="<%= items_path %>">Pictures</a>
          </li>
          <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Panier", cart_path(current_user.id), method: :get, remote: true, class: "nav-link" %>
          </li>
          <% end %>
          <li class="nav-item">
            <a class="nav-link" href="contact#index">Contact</a>
          </li>
          <li class="nav-item dropdown">
            <% if user_signed_in? %>
              <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">My profile <%= current_user.username if current_user.username %></a>
            <% else %>
              <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">User</a>
            <% end %>
            <div class="dropdown-menu">
              <% if user_signed_in? %>
                <a class="dropdown-item text-black" href="<%=user_path(current_user.id)%>">My profile</a>
              <% else %>
                <%= link_to "Sign in", new_user_session_path, method: :get, class: "dropdown-item text-black" %>
              <% end %>
              <div class="dropdown-divider"></div>
              <% unless user_signed_in? %>
                <a class="dropdown-item text-black" href="<%= new_user_registration_path %>">Sign up</a>
              <% else %>
                <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item text-black" %>
              <% end %>
            </div>
          </li>
          <li>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M290.59 192c-20.18 0-106.82 1.98-162.59 85.95V192c0-52.94-43.06-96-96-96-17.67 0-32 14.33-32 32s14.33 32 32 32c17.64 0 32 14.36 32 32v256c0 35.3 28.7 64 64 64h176c8.84 0 16-7.16 16-16v-16c0-17.67-14.33-32-32-32h-32l128-96v144c0 8.84 7.16 16 16 16h32c8.84 0 16-7.16 16-16V289.86c-10.29 2.67-20.89 4.54-32 4.54-61.81 0-113.52-44.05-125.41-102.4zM448 96h-64l-64-64v134.4c0 53.02 42.98 96 96 96s96-42.98 96-96V32l-64 64zm-72 80c-8.84 0-16-7.16-16-16s7.16-16 16-16 16 7.16 16 16-7.16 16-16 16zm80 0c-8.84 0-16-7.16-16-16s7.16-16 16-16 16 7.16 16 16-7.16 16-16 16z"/></svg>
          </li>
        <ul>
      </div>
    </div>

app/views/application/_profile.html.erb
<br><div class="container mt-1 parent">
    <div class="row d-flex justify-content-center">
        <div class="col-md-5">
            <div class="card p-1 py-1">
                <div class="text-center"> <img src="https://images.chienchatetcompagnie.fr/Produits/256/1604172_WEB1.jpg" width="100" class="rounded-circle"> </div>
                <div class="text-center mt-3"> <span class="bg-secondary p-1 px-4 rounded text-white">Pro</span>
                    <h5 class="mt-2 mb-0">JCVD</h5> <span>UI/UX Designer</span>
                    <div class="px-4 mt-1">
                        <p class="fonts">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
                    </div>
                    <ul class="social-list">
                    </ul>
                    <div class="buttons"> <button class="btn btn-warning px-4">Message</button> <button class="btn btn-warning px-4 ms-3">Contact</button></div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/application/_session_edit.html.erb
<h2>Edit <%= resource_name.to_s.humanize %></h2>

<%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :email, required: true, autofocus: true %>

    <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
      <p>Currently waiting confirmation for: <%= resource.unconfirmed_email %></p>
    <% end %>

    <%= f.input :password,
                hint: "leave it blank if you don't want to change it",
                required: false,
                input_html: { autocomplete: "new-password" } %>
    <%= f.input :password_confirmation,
                required: false,
                input_html: { autocomplete: "new-password" } %>
    <%= f.input :current_password,
                hint: "we need your current password to confirm your changes",
                required: true,
                input_html: { autocomplete: "current-password" } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Update" %>
  </div>
<% end %>

<h3>Cancel my account</h3>

<p>Unhappy? <%= link_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete %></p>

<%= link_to "Back", :back %>

app/views/application/_sign_up.html.erb
<div class="login-body">   
  <div class="login-outer border border-warning">
    <div class="sign-up" >
    <br><h2>Sign up<b class="text-warning">.</b></h2><br>

<%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= f.error_notification %>

<div class="form-group mb-4">
    <%= f.input :email,
                required: true,
                autofocus: true,
                input_html: { autocomplete: "email" }%>
                </div>

<div class="form-group mb-4">
    <%= f.input :password,
                required: true,
                hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                input_html: { autocomplete: "new-password" } %>
                </div>

<div class="form-group mb-4">
    <%= f.input :password_confirmation,
                required: true,
                input_html: { autocomplete: "new-password" } %>
                </div>

<div class="form-actions">
    <%= f.button :submit, "Sign up", class: "btn btn-lg btn-warning btn-block" %>
</div><br>

<% end %>

<%= render "devise/shared/links" %>
</div>
</div>
</div>

app/views/application/_updated_cart.html.erb
<div class="updated-cart-body border border-warning" id="cart">
    <div class="cart-title">
        <h4>Panier</h4>
    </div>
    <div class="cart-elements">
        <% @cart.each do |item| %>
            <div>
                <a href="<%= new_charge_path %>" class="nav-link text-dark" ><%= Item.find(item.item_id).name %><br>$<%= item.price %></a>
                <%= link_to "Enlever", cart_path(item.id), method: :delete, remote: true, class: "nav-link text-danger" %>
            </div>
        <% end %>
    </div>
    <div class="bottom-payment">
        <%= link_to "Total : $#{cart_total}", carts_path, method: :get, class: "btn btn-sm btn-warning" %>
    </div>
</div>